
# variables:
#   PROJECT_PATH: "$CI_PROJECT_DIR"
#   APP_OUTPUT_PATH: "$CI_PROJECT_DIR/dist/ems"
#   OUTPUT_PATH: "$CI_PROJECT_DIR/artifacts"

# stages:
#   - install
#   - build
#   - test

# install_dependencies:
#   stage: install
#   image: node:12-alpine
#   tags:
#     - docker
#   script:
#     - npm install
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules
#     policy: pull
#   only:
#     refs:
#       - merge_requests
#       - master
#     changes:
#       - package-lock.json

# build_app:
#   stage: build
#   image: node:12-alpine
#   tags:
#     - docker
#   script:
#     - npm ng build 
#   after_script:
#     - cp $PROJECT_PATH/Dockerfile $APP_OUTPUT_PATH
#   artifacts:
#     name: "angular-app-pipeline"
#     paths:
#       - $APP_OUTPUT_PATH
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules
#     policy: pull
